### PR TITLE
Updating tensorflow version

### PR DESCRIPTION
**Pull request by ymt123**

### CODE REVIEW

**Comment by agude** [comment]
Do we need to update CUDA or cuDNN for TF10?

**Comment by ymt123** [comment]
Good questions. We want to stick to CUDA 7.5 so we can use the precompiled Tensorflow (rather than the pain of building it from scratch). We could upgrade cuDNN versions if we want though.

**Comment by agude** [comment]
I think we should make the minimal change that will get #86 to work.

**Comment by ymt123** [comment]
I think that what is checked in now is the minimal change

**Pull request merged**
