### PR TITLE
Cross eval

### PR DESCRIPTION
**Pull request by ymt123**
Updates to cross eval. Fixing a bug that applied to many of the algorithms and adding support for optimizing word vectors.

### CODE REVIEW

**Comment by karllab41** [comment]
With optim_words turned to False, the following error occurs:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-01dc2a749b3d> in <module>()
      1 logger.info("Preparing test_dataset.")
----> 2 fetches, feed_dict, truth = model.prep_predict(test_dataset)

/local_data/kni/_branch_examine/verify_optim/verify_refactor/attalos/imgtxt_algorithms/approaches/negsampling.pyc in prep_predict(self, dataset, cross_eval)
    282 
    283             # Only do this if necessary
--> 284             if len(self.overlap_test):
    285                 self.test_w[ self.overlap_test ] = self.w[ self.overlap_train ]
    286 

AttributeError: 'NegSamplingModel' object has no attribute 'overlap_test'

**Comment by karllab41** [comment]
Unfortunate. Current iterations using set difference and set unions is not producing the exact same results...

**Comment by karllab41** [comment]
The reason for the performance degradation is that prep_predict gets called by `main.py` only once. Since we're updating the `w` matrix every-time, this really belongs in `predict` if we actually take the evaluation code seriously.

**Comment by ymt123** [comment]
@karllab41 Updated PR with a fix to the issue you found

**Pull request merged**
