### PR TITLE
Add demo correlation notebooks.

### PR DESCRIPTION
**Pull request by kylemvz**
- Add octave code for evaluation. (9cc3aa0)
- Add __init__.py file to imgtxt_algorithms. (0d892bb)
- Add demo correlation notebooks. (a396387)

I'll submit another PR with util functions pulled out into a separate .py file.

### CODE REVIEW

**Comment by kylemvz** [comment]
- Moving correlation util functions to a separate file. (fab6cd4)

**Comment by ymt123** [comment]
It's fine to not use the dataset iterators for experiments but can you explain how to download/generate the following files?

iaprtc_alexfc7.npz
iaprtc_dictionary.txt
iaprtc_trainlist.txt
iaprtc_testlist.txt

**Comment by kylemvz** [comment]
@karllab41: Could you please add a comment about how you generated those files? I took that code block from your fork.

**Comment by kylemvz** [comment]
I'd like to finish this PR so that I can merge in my TextTransformer changes. I'll create a new PR afterwards to continue my work.

The only potential place where this PR may make breaking changes is in the TextTransformer.py and OneHot.py changes, but assuming that no one was using these classes before, then this shouldn't affect any other files in the repo.

**Pull request merged**
