### PR TITLE
Adding Direct Regression

### PR DESCRIPTION
**Pull request by ymt123**
Adding direct regression algorithm.

### CODE REVIEW

**Comment by ymt123** [comment]
Right now I'm summing the word vectors (rather than randomly picking a word vector) which causes this to not converge. I'm still working on why it doesn't converge but I wanted to make this a little more visible.

**Comment by karllab41** [comment]
Nice. Let's evaluate on the full dataset. Also, if you're using a different evaluation code than the MATLAB code, then you should verify that they produce the same results since you're writing your own code...

**Comment by ymt123** [comment]
@karllab41 Now validating over the entire dataset.

**Comment by karllab41** [comment]
The regression part looks good; I think there's a lot that can be used. I tried it out, and am getting fairly good results with one-hot encoding. That DNNRegressor function is a beast! Here are my notes:

- There are a few places where a bit more linear algebra (e.g., matrix ops for correlation analysis)  instead of more CS constructs like MinHeap. Not a big deal, but it cuts down on a lot of code.

- Unfortunately, your evaluation code does not match the standard Octave code in tag prediction (it is receiving on average 10% higher P/R), so we'll have to parse out what's going on there.

- You had a iPython Notebook. That seems useful for documentation and eventually people who would like to use it.

- One thing that I need, and perhaps you've already written: a way for to trace back to the original image. I suppose this would be part of the Dataset class, where a unique identifier would trace the feature back to the original image.

**Comment by ymt123** [comment]
Updated code to rely on attalos.evaluation.evaluation code. Unfortunately rebasing pushed all the commits to the end.

Direct comments:
- Moved to more linear algebra like constructs (argpartition does what I wanted which was avoiding sorting the whole vector)
- Now relying on on the evaluation code so any miss match is sort of OBE (I did some poking into why they weren't matching separately)
- We can add notebooks but I think the bigger thing is to add a README.md to the imgtxt_algoritms that has how to run the various scripts (since the scripts should be somewhat self contained)
- I think I'd like to keep the dataset and dataset_prep objects separate. I think not having to have the raw data in the dataset class is a good thing (since the dataset objects are much smaller than the raw data). I'll add the snippet to do this to this thread (in a separate comment)
- The entire dataset is evaluated at line 112 (iterating over the test dataset)

**Comment by ymt123** [comment]
This is focused on doing this in an Jupyter Notebook but it should be pretty straightfoward to adapt to a non-notebook environment:

```python
from IPython.display import Image
from attalos.dataset.dataset import Dataset
image_feature_file = '/<path/to/features>/image/mscoco_train2014_inception_uncompressed_0701.hdf5'
text_feature_file = '/<path/to/features>/features/text/mscoco_train2014_text.json.gz'
mscoco_train_dataset = Dataset(image_feature_file, text_feature_file)

from attalos.dataset.mscoco_prep import MSCOCODatasetPrep
mscoco_prep = MSCOCODatasetPrep('/<path/to/raw/data>/MSCOCO', split='train')

index = 316 # This is literally an index into the dataset class going from 0 to num_images (could just be random)
# get features
image_feat, text_tags = mscoco_train_dataset.get_index(index)
word_feat = tags_2_vec(text_tags, w2v_lookup) # Get word vectors for each tag and sum word vectors for an image
# Normalize
image_feat = np.reshape(image_feat/np.linalg.norm(image_feat), (1,2048))
# Get Image Id (vs index) -- map dataset to dataset_prep
image_id = mscoco_train_dataset.image_ids[index]
# Get prediction
pred = dnn_regressor.predict(image_feat)
topk = get_top_k(pred/np.linalg.norm(pred), w2v_lookup, 5, verbose=True)
print 'Truth Tags:\t', '\n\t\t'.join(text_tags)
print
print 'Predicted:\t', '\n\t\t'.join([ '%s:%02.3f'%(item, score) for (score, item) in topk])
mscoco_prep.extract_image_to_location(int(image_id), '/tmp/foo.jpg')
Image('/tmp/foo.jpg')```

**Pull request merged**
