### PR TITLE
Reformat and fixup Dockerfile.nvidia

### PR DESCRIPTION
**Pull request by agude**
There were a few potential problems and formatting oddities that have
been fixed, including:

- Spacing and indenting of `apt-get` commands
- Indenting of several Docker commands
- Added variables to track exact library versions
- Add several locations to the `$PATH`, `$LD_LIBRARY_PATH`, and
  `$LIBRARY_PATH` variables
- Various spacing and tab related errors

### CODE REVIEW

**Comment by agude** [comment]
Running build tests now, please hold.

**Comment by agude** [comment]
I get an error in Dockerfile.torch:

```Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.```

@karllab41 did this work before?

**Comment by agude** [comment]
One of our collaborators is reporting that the torch docker fails without this patch.

**Comment by cobie8a** [comment]
https://github.com/Lab41/attalos/blob/master/Dockerfile.densecap ln61 seems to be causing problems

**Comment by cobie8a** [comment]
here's the error:
`Step 22 : RUN luarocks install https://raw.githubusercontent.com/jcjohnson/torch-rnn/master/torch-rnn-scm-1.rockspec
 ---> Running in 1fa7d40d22f5
Cloning into 'torch-rnn'...
Using https://raw.githubusercontent.com/jcjohnson/torch-rnn/master/torch-rnn-scm-1.rockspec... switching to 'build' mode
Updating manifest for /root/torch/install/lib/luarocks/rocks
torch-rnn scm-1 is now built and installed in /root/torch/install/ (license: MIT)

 ---> debdad6a31b9
Removing intermediate container 1fa7d40d22f5
Step 23 : RUN luarocks install loadcaffe
 ---> Running in 49ea1a7add60
Cloning into 'loadcaffe'...
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /root/torch/install
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_loadcaffe-1.0-0-9452/loadcaffe/build
[ 33%] Running C++ protocol buffer compiler on caffe.proto
Scanning dependencies of target loadcaffe
[ 66%] Building CXX object CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o
[100%] Building CXX object CMakeFiles/loadcaffe.dir/caffe.pb.cc.o
Linking CXX shared module libloadcaffe.so
[100%] Built target loadcaffe
[100%] Built target loadcaffe
Install the project...
-- Install configuration: "Release"
-- Installing: /root/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0/lib/libloadcaffe.so
-- Set runtime path of "/root/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0/lib/libloadcaffe.so" to "$ORIGIN/../lib:/root/torch/install/lib"
-- Installing: /root/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0/lua/loadcaffe/loadcaffe.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0/lua/loadcaffe/ffi.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0/lua/loadcaffe/test.lua
-- Installing: /root/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0/lua/loadcaffe/init.lua
Installing https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec... switching to 'build' mode
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/root/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/root/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0"; 
make
   
cd build && make install
Updating manifest for /root/torch/install/lib/luarocks/rocks
loadcaffe 1.0-0 is now built and installed in /root/torch/install/ (license: BSD)

 ---> b90f8ba3237d
Removing intermediate container 49ea1a7add60
Step 24 : RUN mkdir /nvidia_cudnn
 ---> Running in 583bd371832c
 ---> 5e88757a262c
Removing intermediate container 583bd371832c
Step 25 : ADD extras/cudnn-7.5-linux-x64-v5.1-rc.tgz /nvidia_cudnn
lstat extras/cudnn-7.5-linux-x64-v5.1-rc.tgz: no such file or directory
make: *** [build] Error 1`

**Comment by ymt123** [comment]
Try something like this:
```bash
# Install cuDNN
RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list
ENV CUDNN_VERSION 5
LABEL com.nvidia.cudnn.version="5"
RUN apt-get update && apt-get install -y --no-install-recommends --force-yes \
	   libcudnn5 \
	   libcudnn5-dev && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by cobie8a** [comment]
thanks that seems to be working...

**Pull request merged**
